debug = false
## This is overridden with the $SECRETS_BASE env in the Dockerfile
# base = "/app/secrets"

## This is overridden with the $SECRETS_S3_DOTENV_PATH env in the Dockerfile
# [s3]
# path = "s3://BUCKET/DIR-PATH"

[logging]
# Can use "text" or "json" currently:
format = "text"

## Update this to send errors to Sentry.io
# [logging.sentry]
# dsn = "https://TOKEN1@sentry.io/TOKEN2"
